# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainkategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Link otomatik alinir lutfen degistirmeyiniz,', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField()),
                ('slug', models.SlugField(blank=True, help_text='Link otomatik alinir lutfen degistirmeyiniz,', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='subkategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Link otomatik alinir lutfen degistirmeyiniz,', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
