# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(default=0),
        ),
    ]
